apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-gitops
    color: blue
  name: hello-gitops-blue
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-gitops
      color: blue
  template:
    metadata:
      labels:
        app: hello-gitops
        color: blue
    spec:
      containers:
        - image: hello-gitops
          name: hello-gitops
          ports:
            - name: http
              containerPort: 8050
          readinessProbe:
            httpGet:
              path: /
              port: 8050
            initialDelaySeconds: 5
            periodSeconds: 5