apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-gitops
  name: hello-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8050
  selector:
    app: hello-gitops
    color: blue
  type: ClusterIP